#!/bin/bash

cd /tmp
rm -r /tmp/iznik.recent
mkdir iznik.recent
cd iznik.recent
git clone https://github.com/Freegle/iznik.git
cd iznik
git log --pretty=format:'%s (%cr)' --abbrev-commit --since="7 days ago" > /tmp/git.log
printf "This is an automated list of the changes to the code in the last 7 days.  If you have any questions about them, please reply to this mail.\n\nHere are the more important ones which would affect members:\n\n" > /tmp/git.mail
grep "^*" /tmp/git.log >> /tmp/git.mail
printf "\n...and here are the ones which are minor, or only affect volunteers in ModTools, or are internal changes that you wouldn't notice:\n\n"  >> /tmp/git.mail
grep -v "^*" /tmp/git.log >> /tmp/git.mail
cat /tmp/git.mail | mail -s "Code changes in the last 7 days" "Freegle-Tech@yahoogroups.com" -aFrom:geeks@ilovefreegle.org
rm /tmp/git.mail
cd /tmp
rm -r iznik.recent