#!/bin/bash
rm -r /tmp/sa_train
mkdir /tmp/sa_train
mkdir /tmp/sa_train/spam
mkdir /tmp/sa_train/ham

cd /var/www/iznik/scripts/cron
hhvm sa_train.php  >> /tmp/sa_train.log 2>&1

sa-learn --spam /tmp/sa_train/spam/ >> /tmp/sa_train.log 2>&1
sa-learn --ham /tmp/sa_train/ham/ >> /tmp/sa_train.log 2>&1
