defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:9.2

version: 2
jobs:
  install-dependencies:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - node_modules
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: node_modules
      - persist_to_workspace:
          root: ~/repo
          paths:
            - node_modules

  lint:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run: npm run lint

  build:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run: npm run build:dev
      - run: mkdir builds && tar cvzf builds/iznik.dev.tar.gz dist
      - store_artifacts:
          path: builds
          destination: builds
      - store_artifacts:
          path: dist/bundlesize.html
          destination: bundlesize.html

workflows:
  version: 2
  build:
    jobs:
      - install-dependencies
      - lint:
          requires:
            - install-dependencies
      - build:
          requires:
            - install-dependencies