defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:9.2

version: 2
jobs:
  install-dependencies:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - node_modules
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: node_modules

  lint:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - node_modules
      - run: npm run lint

  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - node_modules
      - run: npm run build:dev
      - run: tar cvzf iznik.dev.tar.gz dist
      - store_artifacts:
          path: iznik.dev.tar.gz
          destination: iznik.dev.tar.gz

workflows:
  version: 2
  build:
    jobs:
      - install-dependencies
      - lint:
          requires:
            - install-dependencies
      - build:
          requires:
            - install-dependencies