#!/bin/bash
#
# Restore the last backup into MySQL.  For use on the archive server.
/etc/init.d/mysql stop
rm -r /archive/mysql
mkdir /archive/mysql
cd /archive/backups
back=`ls -1tr *gz | tail -1`
cd /archive/mysql
tar -xvzf /archive/backups/$back
innobackupex --apply-log /archive/mysql
chown -R mysql:mysql /archive/mysql
/etc/init.d/mysql start
