// We load everything using require.  We need some shims for scripts which aren't AMD-compatible.
requirejs.config({
    baseUrl: "/js/lib",

    urlArgs: "bust=" +  (new Date()).getTime(),

    shim : {
        "bootstrap" : [ 'jquery' ],
        "bootstrap-select": [ "bootstrap" ],
        "bootstrap-switch": [ "bootstrap" ],
        "bootstrap-tagsinput": [ "bootstrap" ],
        "wicket": [ "jquery" ],
        "wicket-gmap3": [ "wicket" ],
        "ga": {
            exports: "ga"
        },
        "waypoints": {
            deps: [ "jquery" ],
            exports: 'Waypoint'
        },
        "jquery.dd": [ "jquery" ],
        "jquery.dotdotdot": [ "jquery" ],
        "jquery.geocomplete": [ "jquery" ],
        "jquery-show-first": [ "jquery" ],
        "fileupload": [ "jquery" ],
        "jquery.ui.widget": [ "jquery" ],
        "iznik/accordionpersist": [ "jquery" ],
        "iznik/selectpersist": [ "jquery" ],

        // Converse
        'crypto.aes':           { deps: ['crypto.cipher-core'] },
        'crypto.cipher-core':   { deps: ['crypto.enc-base64', 'crypto.evpkdf'] },
        'crypto.enc-base64':    { deps: ['crypto.core'] },
        'crypto.evpkdf':        { deps: ['crypto.md5'] },
        'crypto.hmac':          { deps: ['crypto.core'] },
        'crypto.md5':           { deps: ['crypto.core'] },
        'crypto.mode-ctr':      { deps: ['crypto.cipher-core'] },
        'crypto.pad-nopadding': { deps: ['crypto.cipher-core'] },
        'crypto.sha1':          { deps: ['crypto.core'] },
        'crypto.sha256':        { deps: ['crypto.core'] },
        'bigint':               { deps: ['crypto'] },
        'strophe.ping':         { deps: ['strophe'] },
        'strophe.disco':        { deps: ['strophe'] },
        'strophe.register':     { deps: ['strophe'] },
        'strophe.roster':       { deps: ['strophe'] },
        'strophe.vcard':        { deps: ['strophe'] },
        'strophe-core':         { exports: 'Strophe' },
        'backbone.overview':    { deps: ['underscore'] },
        'utils':                { deps: ['jed'] },
        'otr':                  { deps: ['eventemitter'] },
        'converse':             { deps: ['strophe'] }
    },

    paths: {
        "bootstrap" :  "//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min",
        "ga": "//www.google-analytics.com/analytics",
        "waypoints": "/js/lib/jquery.waypoints",
        "fileupload": "/js/lib/jquery-file-upload/jquery.fileupload",
        "jquery.ui.widget": "/js/lib/jquery-file-upload/vendor/jquery.ui.widget",
        "underscore": "/js/lib/underscore",
        "../underscore": "/js/lib/underscore",

        // Converse
        "converse":                 "/js/lib/converse/converse",
        "converse-dependencies":    "/js/lib/converse/src/deps-full",
        "converse-templates":       "/js/lib/converse/src/templates",
        "utils":                    "/js/lib/converse/src/utils",
        "polyfill":                 "/js/lib/converse/src/polyfill",
        "otr":                      "/js/lib/converse/src/otr",
        "bigint":                   "/js/lib/converse/src/bigint",
        "crypto":                   "/js/lib/converse/src/crypto",

        // Crypto, used by converse
        "crypto.aes":           "/js/lib/crypto-js/src/aes",
        "crypto.cipher-core":   "/js/lib/crypto-js/src/cipher-core",
        "crypto.core":          "/js/lib/crypto-js/src/core",
        "crypto.enc-base64":    "/js/lib/crypto-js/src/enc-base64",
        "crypto.evpkdf":        "/js/lib/crypto-js/src/evpkdf",
        "crypto.hmac":          "/js/lib/crypto-js/src/hmac",
        "crypto.md5":           "/js/lib/crypto-js/src/md5",
        "crypto.mode-ctr":      "/js/lib/crypto-js/src/mode-ctr",
        "crypto.pad-nopadding": "/js/lib/crypto-js/src/pad-nopadding",
        "crypto.sha1":          "/js/lib/crypto-js/src/sha1",
        "crypto.sha256":        "/js/lib/crypto-js/src/sha256",        
        
        // moment, used by converse
        "moment_with_locales":      "/js/lib/moment-with-locales/moment_locales",
        'moment_af':                "/js/lib/moment-with-locales/locale/af",
        'moment_de':                "/js/lib/moment-with-locales/locale/de",
        'moment_es':                "/js/lib/moment-with-locales/locale/es",
        'moment_fr':                "/js/lib/moment-with-locales/locale/fr",
        'moment_he':                "/js/lib/moment-with-locales/locale/he",
        'moment_hu':                "/js/lib/moment-with-locales/locale/hu",
        'moment_id':                "/js/lib/moment-with-locales/locale/id",
        'moment_it':                "/js/lib/moment-with-locales/locale/it",
        'moment_ja':                "/js/lib/moment-with-locales/locale/ja",
        'moment_nb':                "/js/lib/moment-with-locales/locale/nb",
        'moment_nl':                "/js/lib/moment-with-locales/locale/nl",
        'moment_pl':                "/js/lib/moment-with-locales/locale/pl",
        'moment_pt-br':             "/js/lib/moment-with-locales/locale/pt-br",
        'moment_ru':                "/js/lib/moment-with-locales/locale/ru",
        'moment_uk':                "/js/lib/moment-with-locales/locale/uk",
        'moment_zh':                "/js/lib/moment-with-locales/locale/zh-cn",
        
        // Strophe, used by converse
        "strophe":                  "/js/lib/strophejs/wrapper",
        "strophe-base64":           "/js/lib/strophejs/base64",
        "strophe-bosh":             "/js/lib/strophejs/bosh",
        "strophe-core":             "/js/lib/strophejs/core",
        "strophe-md5":              "/js/lib/strophejs/md5",
        "strophe-polyfill":         "/js/lib/strophejs/polyfills",
        "strophe-sha1":             "/js/lib/strophejs/sha1",
        "strophe-utils":            "/js/lib/strophejs/utils",
        "strophe-websocket":        "/js/lib/strophejs/websocket",
        "strophe.disco":            "/js/lib/strophejs-plugins/disco/strophe.disco",
        "strophe.ping":             "/js/lib/strophejs-plugins/ping/strophe.ping",
        "strophe.rsm":              "/js/lib/strophejs-plugins/rsm/strophe.rsm",
        "strophe.vcard":            "/js/lib/strophejs-plugins/vcard/strophe.vcard",
        
        "action":                   "/js/lib/converse/src/templates/action",
        "add_contact_dropdown":     "/js/lib/converse/src/templates/add_contact_dropdown",
        "add_contact_form":         "/js/lib/converse/src/templates/add_contact_form",
        "change_status_message":    "/js/lib/converse/src/templates/change_status_message",
        "chat_status":              "/js/lib/converse/src/templates/chat_status",
        "chatarea":                 "/js/lib/converse/src/templates/chatarea",
        "chatbox":                  "/js/lib/converse/src/templates/chatbox",
        "chatroom":                 "/js/lib/converse/src/templates/chatroom",
        "chatroom_password_form":   "/js/lib/converse/src/templates/chatroom_password_form",
        "chatroom_sidebar":         "/js/lib/converse/src/templates/chatroom_sidebar",
        "chatrooms_tab":            "/js/lib/converse/src/templates/chatrooms_tab",
        "chats_panel":              "/js/lib/converse/src/templates/chats_panel",
        "choose_status":            "/js/lib/converse/src/templates/choose_status",
        "contacts_panel":           "/js/lib/converse/src/templates/contacts_panel",
        "contacts_tab":             "/js/lib/converse/src/templates/contacts_tab",
        "controlbox":               "/js/lib/converse/src/templates/controlbox",
        "controlbox_toggle":        "/js/lib/converse/src/templates/controlbox_toggle",
        "field":                    "/js/lib/converse/src/templates/field",
        "form_captcha":             "/js/lib/converse/src/templates/form_captcha",
        "form_checkbox":            "/js/lib/converse/src/templates/form_checkbox",
        "form_input":               "/js/lib/converse/src/templates/form_input",
        "form_select":              "/js/lib/converse/src/templates/form_select",
        "form_textarea":            "/js/lib/converse/src/templates/form_textarea",
        "form_username":            "/js/lib/converse/src/templates/form_username",
        "group_header":             "/js/lib/converse/src/templates/group_header",
        "info":                     "/js/lib/converse/src/templates/info",
        "login_panel":              "/js/lib/converse/src/templates/login_panel",
        "login_tab":                "/js/lib/converse/src/templates/login_tab",
        "message":                  "/js/lib/converse/src/templates/message",
        "new_day":                  "/js/lib/converse/src/templates/new_day",
        "occupant":                 "/js/lib/converse/src/templates/occupant",
        "pending_contact":          "/js/lib/converse/src/templates/pending_contact",
        "pending_contacts":         "/js/lib/converse/src/templates/pending_contacts",
        "register_panel":           "/js/lib/converse/src/templates/register_panel",
        "register_tab":             "/js/lib/converse/src/templates/register_tab",
        "registration_form":        "/js/lib/converse/src/templates/registration_form",
        "registration_request":     "/js/lib/converse/src/templates/registration_request",
        "requesting_contact":       "/js/lib/converse/src/templates/requesting_contact",
        "requesting_contacts":      "/js/lib/converse/src/templates/requesting_contacts",
        "room_description":         "/js/lib/converse/src/templates/room_description",
        "room_item":                "/js/lib/converse/src/templates/room_item",
        "room_panel":               "/js/lib/converse/src/templates/room_panel",
        "roster":                   "/js/lib/converse/src/templates/roster",
        "roster_item":              "/js/lib/converse/src/templates/roster_item",
        "search_contact":           "/js/lib/converse/src/templates/search_contact",
        "select_option":            "/js/lib/converse/src/templates/select_option",
        "status_option":            "/js/lib/converse/src/templates/status_option",
        "toggle_chats":             "/js/lib/converse/src/templates/toggle_chats",
        "toolbar":                  "/js/lib/converse/src/templates/toolbar",
        "trimmed_chat":             "/js/lib/converse/src/templates/trimmed_chat",        

        "iznik": "/js/iznik"
    },

    tpl: {
        // Configuration for requirejs-tpl
        // Use Mustache style syntax for variable interpolation
        templateSettings: {
            evaluate : /\{\[([\s\S]+?)\]\}/g,
            interpolate : /\{\{([\s\S]+?)\}\}/g
        }
    },

    waitSeconds: 0    
});