#!/bin/bash
#

# Who wants to know when the backup failed, or
# when the binary logs didn't get applied
EMAIL=geek-alerts@ilovefreegle.org

# Where you keep your backups
BACKUPDIR=/backups

# path to innobackupex
XTRABACKUP=/usr/bin/innobackupex

# Get user and password
SQLUSER=`grep user ~/.my.cnf | awk -F= '{print $2}'`
SQLPASSWORD=`grep password ~/.my.cnf | awk -F= '{print $2}'`
OPTIONS="--user=$SQLUSER --password=$SQLPASSWORD"

APPLY_LOG_OPTIONS="--apply-log"
BACKUP="$XTRABACKUP $OPTIONS $BACKUPDIR"
APPLY_BINARY_LOG="$XTRABACKUP $OPTIONS $APPLY_LOG_OPTIONS"

# run a backup
$BACKUP

if [ $? == 0 ]; then

  # we got a backup, now we need to apply the binary logs
  MOST_RECENT=`ls -rt $BACKUPDIR | tail -n1`
  $APPLY_BINARY_LOG $BACKUPDIR/$MOST_RECENT

  if [ $? == 0 ]; then
    # Compress
    find $BACKUPDIR/$MOST_RECENT/* -exec gzip {} \;

    # Offsite - you might need to change this.
    gsutil cp -r /backups/ gs://freegle_backup > /tmp/gsutil.out 2>&1

    if [ $? == 0 ]; then
        mail -s "BACKUP SUCCESS: backed up to $BACKUPDIR/$MOST_RECENT" $EMAIL

        # Remove to keep local disk space down.
        rm -r $BACKUPDIR/*
    else
        mail -s "BACKUP ERROR: gsutil copy failed" $EMAIL
    fi
  else
    echo "Couldn't apply the binary logs to the backup $BACKUPDIR/$MOST_RECENT" | mail -s "BACKUP ERRO: Mysql binary log didn't get applied to backup" $EMAIL
  fi

else
   # problem with initial backup :(
   echo "Couldn't do a mysql backup" | mail -s "BACKUP ERROR: Mysql backup failed" $EMAIL
fi