#!/bin/bash
EMAIL=geek-alerts@ilovefreegle.org

# path to innobackupex
XTRABACKUP=/usr/bin/innobackupex

# User and password are in [xtrabackup] in ~/.my.cnf
OPTIONS="--stream=tar /backup"
BACKUP="$XTRABACKUP $OPTIONS $BACKUPDIR"

timestamp=$(date +%Y-%m-%d-%H-%M)

pregp mysql
if [ $? == 0 ]; then
    # run a backup and stream the output directly to Google storage
    $BACKUP | /root/gsutil/gsutil cp - gs://freegle_backup/iznik-$timestamp.tar > /tmp/gsutil.out 2>&1

    if [ $? == 0 ]; then
      grep "0 B" /tmp/gsutil.out
      if [ $? == 0 ]; then
        cat /tmp/gsutil.out | mail -s "BACKUP ERROR: MySQL backup was empty" $EMAIL
      else
        cat /tmp/gsutil.out | mail -s "BACKUP SUCCESS: MySQL backed up to $BACKUPDIR/$MOST_RECENT" $EMAIL
      fi
    else
       # problem with initial backup :(
       echo "Couldn't do a mysql backup" | mail -s "BACKUP ERROR: MySQL backup failed" $EMAIL
    fi

    # ...and one to our archive server
    $BACKUP | ssh root@archive \ "cat - > /archive/backups/iznik-$timestamp.tar"
else
    echo "MySQL not running"| mail -s "BACKUP ERROR: MySQL not running" $EMAIL
fi

