#!/bin/bash
mysql --defaults-file=/root/.my.cnf -e "show status like 'wsrep%';" | grep wsrep_cluster_status | grep non-Primary
rc=$?

# Accept errors often clear, so restarting is premature
#if [ $rc -eq 1 ]
#then
#    tail /var/lib/mysql/*err | grep "Error in accept"
#    rc=$?
#fi

exit $rc