#!/bin/bash
EMAIL=geek-alerts@ilovefreegle.org
#
# Restore the last backup into MySQL.  For use on the archive server.
/etc/init.d/mysql stop
killall -9 mysqld
sleep 10
rm -r /archive/mysql
mkdir /archive/mysql
cd /archive/backups
back=`ls -1tr *gz | tail -1`
cd /archive/mysql
nice tar -xvzf /archive/backups/$back
nice innobackupex --apply-log /archive/mysql
chown -R mysql:mysql /archive/mysql
/etc/init.d/mysql start
sleep 300
maxdate=`mysql --execute="use iznik; SELECT MAX(arrival) FROM messages;" | grep -`
if [ $? == 0 ]; then
    cat /tmp/restore.out | mail -s "RESTORE: DB restored on archive update $maxdate" $EMAIL
else
    cat /tmp/restore.out | mail -s "RESTORE: FAILED on hub" $EMAIL
fi